name: Release

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "5 * * * *"
on:
  workflow_dispatch:
    inputs:
      alphaVersion:
        description: "alpha version."
        required: true
      version:
        description: "release version."
        required: true

jobs:
  release:
    name: release
    runs-on: windows-latest

    steps:
      - name: init
        uses: actions/checkout@v1

      - name: download
        id: package
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{inputs.alphaVersion}}
          fileName: "*"
          out-file-path: "release"

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{inputs.version}}
          name: ${{inputs.version}}
          draft: false
          prerelease: true
          fail_on_unmatched_files: false
          append_body: true
          files: release/*
